PREFIX rdfs:   <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX schema: <https://schema.org/> 
PREFIX ma:     <https://mediaarts-db.bunka.go.jp/data/property#> 
PREFIX class:  <https://mediaarts-db.bunka.go.jp/data/class#> 
 
SELECT 
    ?メディアアート催事 ?ラベル ?開始年月日 ?終了年月日 ?説明文 
WHERE { 
    ?メディアアート催事 schema:genre ?ジャンル ; 
        rdfs:label ?ラベル ; 
        schema:startDate ?開始年月日 ; 
        schema:description ?説明文 . 
    FILTER ( 
        (?ジャンル = "メディアアート催事" || ?ジャンル = "メディアアート展示・実
演") && 
        ( 
            CONTAINS(LCASE(?ラベル), "体験") || 
            CONTAINS(LCASE(?説明文), "体験") || 
            CONTAINS(LCASE(?ラベル), "参加") || 
            CONTAINS(LCASE(?説明文), "参加") 
         ) 
) 
OPTIONAL { ?メディアアート催事 schema:endDate ?終了年月日 } 
}
